"""
SecureCodeGuard – Report Exporter

Exports ReviewReports as Markdown and JSON files.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from app.config import get_settings
from app.models import ReviewReport

logger = logging.getLogger(__name__)


def export_json(report: ReviewReport, output_path: Optional[str] = None) -> str:
    """Export a review report as JSON."""
    settings = get_settings()
    if output_path is None:
        reports_dir = settings.resolve_path(settings.reports_dir)
        reports_dir.mkdir(parents=True, exist_ok=True)
        output_path = str(
            reports_dir / f"review_{report.review_id}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.json"
        )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report.model_dump_json(indent=2))

    logger.info("Exported JSON report to %s", output_path)
    return output_path


def export_markdown(report: ReviewReport, output_path: Optional[str] = None) -> str:
    """Export a review report as Markdown."""
    settings = get_settings()
    if output_path is None:
        reports_dir = settings.resolve_path(settings.reports_dir)
        reports_dir.mkdir(parents=True, exist_ok=True)
        output_path = str(
            reports_dir / f"review_{report.review_id}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.md"
        )

    lines = []
    lines.append("# SecureCodeGuard – Code Review Report")
    lines.append("")
    lines.append(f"> **⚠️ {report.disclaimer}**")
    lines.append("")
    lines.append(f"- **Review ID:** {report.review_id}")
    lines.append(f"- **Timestamp:** {report.timestamp}")
    lines.append(f"- **Source File:** {report.source_file}")
    lines.append(f"- **Review Type:** {report.review_type}")
    lines.append(f"- **Model Used:** {report.model_used}")
    lines.append(f"- **Overall Risk:** {report.overall_risk.value}")
    lines.append(f"- **Total Findings:** {len(report.findings)}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(report.summary)
    lines.append("")

    if report.findings:
        lines.append("## Findings")
        lines.append("")

        # Summary table
        lines.append("| # | ID | Severity | Category | Title | Status |")
        lines.append("|---|-----|----------|----------|-------|--------|")
        for i, f in enumerate(report.findings, 1):
            lines.append(
                f"| {i} | {f.finding_id} | {f.severity.value} | "
                f"{f.category} | {f.title} | {f.status.value} |"
            )
        lines.append("")

        # Detailed findings
        for i, f in enumerate(report.findings, 1):
            lines.append(f"### Finding {i}: {f.title}")
            lines.append("")
            lines.append(f"- **ID:** {f.finding_id}")
            lines.append(f"- **Category:** {f.category}")
            lines.append(f"- **Severity:** {f.severity.value}")
            lines.append(f"- **File:** {f.file}")
            if f.function:
                lines.append(f"- **Function:** {f.function}")
            if f.line_start is not None:
                line_range = str(f.line_start)
                if f.line_end and f.line_end != f.line_start:
                    line_range += f"–{f.line_end}"
                lines.append(f"- **Lines:** {line_range}")
            lines.append(f"- **Confidence:** {f.confidence:.0%}")
            lines.append(f"- **Status:** {f.status.value}")
            lines.append("")

            lines.append("**Evidence:**")
            lines.append(f"```")
            lines.append(f"{f.evidence}")
            lines.append(f"```")
            lines.append("")

            if f.reasoning:
                lines.append("**Reasoning:**")
                lines.append(f"{f.reasoning}")
                lines.append("")

            if f.rule_refs:
                lines.append(f"**Rule References:** {', '.join(f.rule_refs)}")
                lines.append("")

            if f.citations:
                lines.append("**Citations:**")
                for c in f.citations:
                    lines.append(f"- [{c.source}] {c.location}: `{c.snippet[:80]}`")
                lines.append("")

            if f.suggested_fix:
                lines.append("**Suggested Fix:**")
                lines.append(f"```")
                lines.append(f"{f.suggested_fix}")
                lines.append(f"```")
                lines.append("")

            lines.append("---")
            lines.append("")
    else:
        lines.append("## No findings reported.")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by SecureCodeGuard at {report.timestamp}*")

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.info("Exported Markdown report to %s", output_path)
    return output_path
